### ISSUE TITLE
UserFixtureのrole_keyが空データあり

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/Users#2]
念のため報告

https://github.com/NetCommons3/Users/blob/master/Test/Fixture/UserFixture.php#L55
https://github.com/NetCommons3/Users/blob/master/Test/Fixture/UserFixture.php#L65
https://github.com/NetCommons3/Users/blob/master/Test/Fixture/UserFixture.php#L75
https://github.com/NetCommons3/Users/blob/master/Test/Fixture/UserFixture.php#L85
### 参考

RoomsプラグインのUserFixtureをマージすれば良さそう
https://github.com/NetCommons3/Rooms/blob/master/Test/Fixture/UserFixture.php

**Comment by s-nakajima** [comment]
共通のFixtureを各々のプラグインに保持しないようにしたため、Closeする
